[build]
  publish = "/"
  command = "echo 'No build command'"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 
        https://cdn.jsdelivr.net 
        https://identity.netlify.com 
        https://unpkg.com;
      style-src 'self' 'unsafe-inline' 
        https://cdn.jsdelivr.net;
      img-src 'self' data: https:;
      font-src 'self' https://cdn.jsdelivr.net;
      connect-src 'self' https:;
      frame-src 'self' https://identity.netlify.com;
    """

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 
        https://cdn.jsdelivr.net 
        https://identity.netlify.com;
      style-src 'self' 'unsafe-inline' 
        https://cdn.jsdelivr.net;
      img-src 'self' data: https:;
      font-src 'self' https://cdn.jsdelivr.net;
    """