[build]
  publish = "/"
  command = "echo 'No build command'"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 
        https://identity.netlify.com 
        https://unpkg.com 
        https://cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline' 
        https://cdn.jsdelivr.net 
        https://cdnjs.cloudflare.com;
      img-src 'self' data: 
        https://images.unsplash.com 
        https://via.placeholder.com;
      font-src 'self' data: 
        https://cdn.jsdelivr.net 
        https://cdnjs.cloudflare.com;
      connect-src 'self' 
        https://api.netlify.com 
        https://identity.netlify.com;
      frame-src 'self' 
        https://identity.netlify.com;
      media-src 'self' data:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 
        https://cdn.jsdelivr.net 
        https://identity.netlify.com
        https://kit.fontawesome.com;
      style-src 'self' 'unsafe-inline' 
        https://cdn.jsdelivr.net
        https://cdnjs.cloudflare.com;
      img-src 'self' data: https:;
      font-src 'self' 
        https://cdn.jsdelivr.net
        https://cdnjs.cloudflare.com
        data:;
    """